-- ============================================================
-- Миграция 002: автоинкремент для id
--
-- FlutterFlow создал таблицы с id bigint БЕЗ identity/serial,
-- поэтому insert без явного id падает с not-null violation.
-- Это блокировало создание заказов и регистрацию мастеров.
-- ============================================================

do $do$
declare
  t         text;
  start_val bigint;
begin
  foreach t in array array['masters', 'orders', 'options', 'price', 'services']
  loop
    -- уже identity — пропускаем, чтобы скрипт можно было запускать повторно
    if exists (
      select 1 from pg_attribute
      where attrelid = format('public.%I', t)::regclass
        and attname = 'id'
        and attidentity <> ''
    ) then
      raise notice 'identity -> %  (уже есть, пропуск)', t;
      continue;
    end if;

    execute format('select coalesce(max(id), 0) + 1 from public.%I', t)
      into start_val;

    execute format(
      'alter table public.%I alter column id add generated by default as identity (start with %s)',
      t, start_val
    );

    raise notice 'identity -> %  (start %)', t, start_val;
  end loop;
end
$do$;
